services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
      - "6380:6380"
  
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "ExamplePassword"
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql


  rabbitmq:
    image: rabbitmq:4.1.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"
  
  backend-one: &backend
    build:
      context: ./Backend/ChatApp
      target: dev
    ports:
      - "9000:8080"
    depends_on:
      - redis
      - postgres
      - rabbitmq
      - cdn
    environment:
      - DbConnectionString=Server=postgres;Port=5432;Database=postgres;User Id=postgres;Password=ExamplePassword;
      - RedisConnectionString=redis
      - RabbitMqHost=rabbitmq
      - JWTConfig__Issuer=AppChatBackend
      - JWTConfig__Audience=AppChatFrontend
      - JWTConfig__SecretKey="ExamplePasswordSha256X84V&&@WF8q4^7fsSWrLCMBF7^QN9SpJ"
      - JWTConfig__ExpirationInMinutes=5
      - InMemorySave__BasePath=/var/www/ChatApp
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - cdn_data:/var/www/ChatApp

  frontend:
    build:
      context: ./FrontEnd
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules 
  
  frontend-nginx:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./FrontEnd/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - loadbalancer
  
  loadbalancer:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx/loadbalancer.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-one
  
  cdn:
    image: nginx:alpine
    ports:
      - "10000:80"
    volumes:
      - ./nginx/cdn.conf:/etc/nginx/nginx.conf
      - cdn_data:/var/www/ChatApp:ro

volumes:
  postgres_data:
  cdn_data: