worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    server {
        listen 80;    
        
        root /var/www/ChatApp;
        
        location /cdn/ {
            alias /var/www/ChatApp/;
            autoindex on;
            if ($request_method !~ ^(GET|HEAD)$ ) {
                            return 405;
            }
            
            try_files $uri =404;
            
            add_header 'Access-Control-Allow-Origin' '*' always;
                        add_header 'Access-Control-Allow-Methods' 'GET, HEAD, OPTIONS' always;
                        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
            
            expires 30d;
            add_header Cache-Control "public, no-transform";
            access_log off;
        }
        
    }
}